# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DogVillage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #Firebase
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  #Image
  pod 'SDWebImage'
  pod 'YPImagePicker'

  #Loading
  pod 'JGProgressHUD'

  #TextView
  pod 'IQKeyboardManagerSwift'

  #Rx
  pod 'RxSwift'
  pod 'RxCocoa'

  #calendar
  pod 'FSCalendar'
  # Pods for DogVillage

end
